name: instituto_frances_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/Horizonta-NBG.png
    - assets/images/Imagotipo-NBG.png
    - assets/images/Imagotipo-Separado-NBG.png
    - assets/images/Horizontal-W-NBG.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/Imagotipo-Separado-NBG.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/Imagotipo-Separado-NBG.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/Imagotipo-NBG.png
  fullscreen: true
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
